version: "3"

services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microfin-net

  transaction-service:
    build: .
    volumes:
      - ./transactions/:/home/node/app
    ports:
      - 5000:5555
    networks:
      - microfin-net
    depends_on:
      - postgres
      - rabbitmq
      - redis

  account-service:
    build: .
    volumes:
      - ./accounts/:/home/node/app
    ports:
      - 5001:5555
    networks:
      - microfin-net
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: "postgres:16-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - microfin-net

  rabbitmq:
    image: rabbitmq:3.12.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - microfin-net

  redis:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microfin-net

networks:
  microfin-net:
    name: microfin-net
    driver: bridge

volumes:
  pg_data:
